### ISSUE TITLE
VS Code - parameter generation in intellisense

### ISSUE THREAD

**Issue by jaredbaszler** [andrewackerman/darq#4]
First of all, GREAT JOB ON THIS PACKAGE.  As someone who is doing a heavy transition from .NET to Flutter/Dart, this package made me do cartwheels in my office late last night.  Thank you so much for the work that you've done  on it.  

I do have a question though and I'm not sure this is something that the package even controls but I'm guessing it does.  When I use intellisense to select one of the package's methods, I get some odd parameter generation.  It would be nice for example in this `.Select` for it to fill in the parameters instead of skipping over them and highlighting the method body instead.  

![image](https://user-images.githubusercontent.com/9924084/98380473-3f62c280-200e-11eb-9cc4-0a47ff1cad9b.png)

Thanks again for your work on this awesome package.

**Comment by andrewackerman** [comment]
My IntelliSense doesn't behave like that when I select a method from the dropdown list for some reason, but I've gone ahead and filled all the function parameter types to have names which I suspect will solve the issue for you.
