### ISSUE TITLE
Null-safety support

### ISSUE THREAD

**Issue by rodion-m** [andrewackerman/darq#5]
Hello! Recently dart announced null-safety feature. Do you plan to add null-safety support to make it sound perfect?

**Comment by andrewackerman** [comment]
Sorry for being a little AWOL for a couple months, but after shoring up the current version and addressing outstanding PRs, I'm going to start working on a preview version with null-safety support. Stay tuned! :)

**Comment by andrewackerman** [comment]
Null safety is now live under version `1.0.0-dev.X`. Note that since the version number has been upgraded to a new major version, previous installs that depend on "^0.5.0" will need to be updated to at least "^1.0.0-dev.1" (_not_ "^1.0.0" as that does not include prerelease versions).

**Comment by rodion-m** [comment]
Since dart 2.12 is released, I think it costs to move null safety package to a release branch.

**Comment by rodion-m** [comment]
@andrewackerman Since dart 2.12 is released, I think it costs to move null safety package to a release branch.

**Comment by Abion47** [comment]
@rodion-m I had some clean-up to do with the `Tuple` classes, but in lieu of any new or outstanding issues, darq is now pushed to full 1.0.0 release.

**Comment by rodion-m** [comment]
Thanks a lot!
